### ISSUE TITLE
official minetestmapper has different syntax from script

### ISSUE THREAD

**Issue by thePalindrome** [est31/leaftest#9]
The geometry option for https://github.com/minetest/minetestmapper needs X:Y+W+H, but the script provides X,Y+W+H (minetestmapper wants a colon, we provide a comma).

Perusing the git logs, it seems it's always mandated a colon, at least since 5 years ago when --geometry was added, so I have no clue how this worked before, since the script is x,y for two years.

Any thoughts on what happened?

**Comment by est31** [comment]
Its a different feature, that's supported by the [fork](https://github.com/Rogier-5/minetest-mapper-cpp). The official minetestmapper has no support for this feature (specifying the coordinates in mapnodes), so there is no way to "fix" the script. I wrote this script in order to map a server which had a spawn at a non mapblock offset, and I think its an important feature to offer to users. See also #8.

**Comment by thePalindrome** [comment]
Ah, my bad. I assumed the one under the minetest name was the one people actually used :P 
Problem with open source, no?

**Comment by est31** [comment]
@thePalindrome just make sure to apply this PR locally: https://github.com/Rogier-5/minetest-mapper-cpp/pull/20
